### ISSUE TITLE
Solicited routes require cluster capabilities, e.g. --cluster.

### ISSUE THREAD

**Issue by vornet** [nats-io/nats-docker#2]
Looks like there's a new undocumented required "--cluster" parameter in 0.8.0.  I have no idea how to use it so reverting back to 0.7.2.

I keep getting this error: https://github.com/nats-io/gnatsd/blob/e124d3010f1ba38113fb2483b6cb4cd4a35fbf2d/main.go#L265

In any case, doc @ https://hub.docker.com/_/nats/ needs to be updated accordingly.

**Comment by derekcollison** [comment]
Thanks for the feedback..

**Comment by kozlovic** [comment]
The parameter `-routes` configures the URLs the server should try to create routes to. The `-cluster` parameter configures the URL the server is accepting route connections on.
Note that the `-cluster` URL is given to other servers so that a full mesh can be formed without explicit configuration.
For instance, server `A` can be configured to explicitly connect to `B`, but if `B` is already connected to `C`, then `C` will connect to `A` (at the `cluster` address) without need for explicit configuration.

For more information I would recommend checking out the NATS Server `Clustering` paragraph at: https://github.com/nats-io/gnatsd/blob/master/README.md

The updated docker doc for the command line options will be:
```
Cluster Options:
        --routes <rurl-1, rurl-2>    Routes to solicit and connect
        --cluster <cluster-url>      Cluster URL for solicited routes
```

**Comment by MichaelErmer** [comment]
The options on the main page are equally outdated unfortunatelly :( http://nats.io/documentation/server/gnatsd-usage/

I think its weird, the --cluster parameter should be optional, given the major version was not updated.

@vornet if you want to run a cluster with docker run it with the follow entrypoint to get the old default behaviour:
    /gnatsd -m 8222 --cluster nats://0.0.0.0:6222 --routes YOURROUTESLIKEBEFORE

**Comment by vornet** [comment]
Thanks!

**Comment by derekcollison** [comment]
@aricart can you work with Lorenzo to get the docs updated? Thanks.

**Comment by aricart** [comment]
Sure thing.




/a

**Comment by kozlovic** [comment]
Closing this issue since both Docker hub "doc", repo's README.md and nats.io's doc have been updated.
