### ISSUE TITLE
Create Alpine image as well now that docker 1.12+ supports healthchecks

### ISSUE THREAD

**Issue by byrnedo** [nats-io/nats-docker#6]
Since the newer docker versions support healthchecks which are run from _within_ the container, it would be great to have an alpine linux image to be able to run netcat for instance.

If there's another way using the gnatsd binary to check if the server is running then please let me know.

Right now I have to resort to copying this repo and changing the FROM section in the dockerfile.

EDIT: I guess something more sophisticated (curl and jq maybe) is need to properly check the healthcheck api

**Comment by kozlovic** [comment]
The problem is what you pick as the health check command. If it is curl, then you may have to have the server running with monitoring pot. As of now, if you provide any command line when running NATS Server docker image, the "default" values specified in `CMD` are ignored. If the health check depends on the monitoring port to be opened and you do not specify it (or change the port number) in the command line, the health check will report the docker image as unhealthy.
Also, default interval/timeout/retries may not be suitable for all, and I think that people would end-up having to rebuild their own image anyway.

**Comment by byrnedo** [comment]
Yeah, I think you're right. It's not so much hassle to just fork the repo
and change the base image. Also, if it came to a nats cluster, would one
also need a separate external health check in that case anyway to provide
any meaningful status?

On 19 Jan 2017 18:32, "Ivan Kozlovic" <notifications@github.com> wrote:

The problem is what you pick as the health check command. If it is curl,
then you may have to have the server running with monitoring pot. As of
now, if you provide any command line when running NATS Server docker image,
the "default" values specified in CMD are ignored. If the health check
depends on the monitoring port to be opened and you do not specify it (or
change the port number) in the command line, the health check will report
the docker image as unhealthy.
Also, default interval/timeout/retries may not be suitable for all, and I
think that people would end-up having to rebuild their own image anyway.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nats-io/nats-docker/issues/6#issuecomment-273842889>,
or mute the thread

**Comment by kozlovic** [comment]
@pires has done some work around that for nats cluster on kubernetes: https://github.com/pires/kubernetes-nats-cluster, you may want to have a look.

We are not saying no to make use of health check, but need to think of a good reliable way of doing it. For instance, the monitoring port, as I described, may not be the best solution. Whatever we do, I think it would have to be indicative of the server's core ability to receive/send messages, in other words, the server may be deadlock'ed, etc.. but the monitoring handling still responding.
