### ISSUE TITLE
The service process could not connect to the service controller.

### ISSUE THREAD

**Issue by Murf** [nats-io/nats-docker#9]
I am getting the following when running nats:nanoserver on Windows 10

PS C:> docker run -d --name nats nats:nanoserver
PS C:> docker ps -a
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
5e894b3d9c0d nats:nanoserver "gnatsd -c gnatsd...." 5 seconds ago Exited (1) Less than a second ago nats

PS C:> docker logs nats
The service process could not connect to the service controller.

**Comment by kozlovic** [comment]
Indeed, we are working on a fix for that with server side: https://github.com/nats-io/gnatsd/pull/544, and one for this repo: https://github.com/nats-io/nats-docker/pull/8.
We are working on some other fixes and will try to release an update as soon as possible.

That being said, **once the 2 above PRs are merged**, you have the ability to generate a new docker image. You would need to clone this repo (if not already done), then call `./update.sh master`. It should update/create executables in the repo. Then, from `windows/nanoserver` directory, build an image:
```
docker build -t=nats-win-fix .
```
Otherwise, please wait for the official update. We apologize for the inconvenience!

**Comment by Murf** [comment]
Thanks, I will build my own and let you know how I go.

**Comment by kozlovic** [comment]
Keep in mind that these PRs are not merged it, although you could work on those branches, etc..

**Comment by kozlovic** [comment]
The 2 PRs have been merged. However, I will keep this issue opened until a new Windows Docker Image is available on Docker Hub. Thanks!

**Comment by kozlovic** [comment]
@Murf A new docker image (1.0.2) is now available and solves the issue. Let me know if it works for you. Thanks!

**Comment by Murf** [comment]
Happy to wait for the merge, thanks

**Comment by kozlovic** [comment]
@Murf It was merged, but the point is that the new version has been released and is available on Docker Hub: https://hub.docker.com/r/library/nats/tags/. Look for tag 1.0.2.

**Comment by Murf** [comment]
Sorry I missed the earlier comments, thanks trying now

**Comment by Murf** [comment]
All working, thanks!
